# Generated by Django 4.0.3 on 2022-03-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=16, unique=True)),
                ('custom_name', models.CharField(blank=True, max_length=32, null=True)),
                ('capacity', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'meeting_room',
            },
        ),
    ]
