# Generated by Django 4.0.5 on 2022-06-09 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meeting_rooms.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='meeting_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='meeting_rooms.meetingroom'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='participants',
            field=models.ManyToManyField(related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_to',
            field=models.DateTimeField(default=meeting_rooms.utils.models.get_default_reservation_end_time),
        ),
    ]
