# Generated by Django 4.0.4 on 2022-05-15 17:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 18, 27, 25, 398916, tzinfo=utc)),
        ),
    ]
