# Generated by Django 4.0.3 on 2022-03-31 18:06
import os

from django.db import migrations
from django.core import serializers


def load_fixture(apps, schema_editor):
    fixture_location = os.path.join(
        os.path.abspath(os.path.join(os.path.dirname(__file__),
                                     '../fixtures')),
        'meeting_room.json'
    )
    with open(fixture_location, 'rb') as fixture:
        objects = serializers.deserialize(
            'json', fixture, ignorenoneexistent=True
        )
        for obj in objects:
            obj.save()


def unload_fixture(apps, schema_editor):
    model = apps.get_model('meeting_rooms', 'MeetingRoom')
    model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
