# Generated by Django 4.0.4 on 2022-05-14 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_rooms.user')),
                ('meeting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_rooms.meetingroom')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
